### ISSUE TITLE
[PY_F_FE001] 음악 플레이 재생

### ISSUE THREAD

**Issue by kimdongju666** [codestates-seb/seb44_main_011#21]
## 📌Feature Description

> 음악 플레이 재생 기능
## ✨ To-do

- [ ] 재생 버튼 클릭 시 음악 재생
- [ ] 이전, 다음 버튼으로 음악 변경
- [ ] 음량 조절 가능

**Additional context**
