### ISSUE TITLE
[MS_BE_001] 회원가입

### ISSUE THREAD

**Issue by KYUNGMINMON** [codestates-seb/seb44_main_011#4]
## 📌Feature Description

회원가입 기능

> description
## ✨ To-do

- [x] 회원가입 시 이메일, 닉네임, 비밀번호를 입력받아야 한다.
- [x] 유효성 검증을 거친다
- 이메일 형식(@, 공백 불가)
- 닉네임 2~7자, 비밀번호 8 ~ 16자(영문자 1, 숫자 1 포함, 한글 불가, 공백 불가)
- [x] 이메일은 중복을 허용하지 않는다.
- [x] 회원가입이 완료되면 정보를 DB 에 저장한다
- [x] 비밀번호는 암호화 과정을 거친 후 DB 에 저장되어야 한다

**Additional context**
