### ISSUE TITLE
[PL_BE_003] 곡 상세조회 기능

### ISSUE THREAD

**Issue by younghoshin** [codestates-seb/seb44_main_011#7]
## 📌Feature Description
곡 상세조회 기능

# ✨ To-do

- [x] 곡의 이름으로 조회가 가능해야 한다.

## 테스트 코드 작성
- [x] 테스크 코드 구현
- [x] 문서화진행
## Advanced
- [x] 필요하다면 곡의 id로도 조회가 가능해야 한다.
