### ISSUE TITLE
[PL_BE_007] 시큐리티 적용 후 코드 리펙토링 작업

### ISSUE THREAD

**Issue by younghoshin** [codestates-seb/seb44_main_011#82]
## 📌Feature Description
시큐리티 적용 후 코드 리펙토링 작업

## ✨ To-do
- [x] PlayList 컨트롤러 및 서비스 리펙토링
- [x] Music 컨트롤러 및 서비스 리펙토링
- [x] PlayList Test code 리펙토링
- [x] Music Test code 리펙토링
